### ISSUE TITLE
US16 - Eu, como usuário, desejo visualizar todos os projetos cadastrados no aplicativo.

### ISSUE THREAD

**Issue by fellipe-araujo** [DiProjOrcestra/orclamp#12]
## Descrição da Issue
Cria tela que mostre todos os projetos disponíveis.

### Tasks:
- [x] Criar tela de projetos de acordo com o protótipo.
- [x] Mostrar todos os projetos cadastrados no aplicativo.
- [x] Campo para pesquisar o nome de um projeto cadastrado.
