### ISSUE TITLE
 US08 - Eu, como usuário, desejo fazer CRUD de Projetos para poder gerenciar projetos no app

### ISSUE THREAD

**Issue by ateldyfilho** [DiProjOrcestra/orclamp#16]
## Descrição da Issue
Usuário criar, ver, atualizar e deletar projeto (backend)

### Tasks: 
- [ ] Usuário criar projeto
- [ ] Usuário ver projeto criado (read)
- [ ] Usuário atualizar projeto criado
- [ ] Usuário deletar projeto já criado
