### ISSUE TITLE
US21 - Eu, como usuário, desejo ter uma tela de visualização dos projetos individuais

### ISSUE THREAD

**Issue by vitorAlves7** [DiProjOrcestra/orclamp#19]
## Descrição da Issue
Ter uma ela de visualização dos projetos individualmente  

### Tasks: 
Todas as atividades a serem realizadas devem estar elencadas em tópicos e ao serem finalizadas devem receber um check.
- [ ] Mostrar a descrição do projeto como imagem,descrição e título
- [ ] Permitir o usuário adicionar comentário
- [ ] Permitir o usuário ir para o próximo projeto

## Labels
A issue deve ser marcada com uma ou mais tags adequadas, para fins de rastreamento do projeto.

## ZenHub
A issue deve ser adicionada à pipeline correspondente no ZenHub, para o acompanhamento de seu progresso.
