### ISSUE TITLE
US23 - Eu, como usuário, desejo ter uma tela de notificações

### ISSUE THREAD

**Issue by vitorAlves7** [DiProjOrcestra/orclamp#21]
## Descrição da Issue
Criar uma tela de notificações

### Tasks: 

- [x] Listar as notificações
- [ ] Aceitar ou não solicitação de novos membros
- [ ] Destacar notificações não visualizadas 

## Labels
A issue deve ser marcada com uma ou mais tags adequadas, para fins de rastreamento do projeto.

## ZenHub
A issue deve ser adicionada à pipeline correspondente no ZenHub, para o acompanhamento de seu progresso.
