### ISSUE TITLE
Criar cluster do codecamp na cloud do mongoDB

### ISSUE THREAD

**Issue by alan-ms** [DiProjOrcestra/orclamp#23]
## Descrição da Issue
Criação da conta com o email da DiProj no clould do mongoDB e outra configurações.

### Tasks:

- [x] Criar conta no clould da mongoDB
- [x] Criação do cluster
- [x] Criação do usuário para acesso ao cluster

**Comment by alan-ms** [comment]
Todas as terefas realizadas.
