### ISSUE TITLE
US27 - Eu, como usuário, desejo ter uma tela de confirmação quando estiver criando um projeto para ver se está tudo ok.

### ISSUE THREAD

**Issue by sudjoao** [DiProjOrcestra/orclamp#35]
## Descrição da Issue
Página de pré-visualização de criação de projeto.

### Tasks: 
- [x] Criar tela de acordo com o protótipo;
- [x] Ter como voltar para modificar os dados;
- [x] Ter como confirmar.
