### ISSUE TITLE
US18 - Eu, como usuário, desejo ter uma tela de criação de projetos para criar projetos

### ISSUE THREAD

**Issue by DiProjOrcestra** [DiProjOrcestra/orclamp#4]
## Descrição da Issue
Produzir tela de criação de projetos de acordo com o protótipo.
### Tasks: 
- [x] Criar tela de acordo com o protótipo;
- [x] Pegar nome do projeto;
- [x] Pegar descrição do projeto;
- [x] Pegar imagem do projeto.

**Comment by fellipe-araujo** [comment]
Versão web finalizada.
