### ISSUE TITLE
US29 - Eu, como usuário, desejo ter uma página para visualizar todos os projetos cadastrados na aplicação.

### ISSUE THREAD

**Issue by fellipe-araujo** [DiProjOrcestra/orclamp#43]
## Descrição
Página com todos os projetos cadastrados.

## Tasks: 
- [x] Página de acordo com o protótipo.
- [x] Possibilidade de criar um novo projeto e também de realizar o logout na aplicação.
- [x] Projetos mostrados em cards.
