### ISSUE TITLE
US19 - Eu, como usuário, desejo ter uma tela de finalização do projeto para conferir se as informações estão todas certas

### ISSUE THREAD

**Issue by DiProjOrcestra** [DiProjOrcestra/orclamp#6]
## Descrição da Issue
Ter uma tela de pre-visualização logo depois que o usuário tiver terminado a história.

### Tasks:
- [ ] Mostrar informações dos projetos, incluindo a imagem que o usuário inseriu;
- [ ] Permitir o usuário voltar para a página de criação;
- [ ] Permitir o usuário finalizar a criação.
