### ISSUE TITLE
US10 - Eu, como usuário desejo comentar em projetos existentes

### ISSUE THREAD

**Issue by DLBrianPina** [DiProjOrcestra/orclamp#7]
## Descrição da Issue
Habilidade de comentar em projetos existentes.

### Tasks: 
- [ ] Field para adicionar comentários
- [ ] Adicionar comentários sobre o projeto
- [ ] Ver comentários sobre o projeto
