### ISSUE TITLE
US20 - Eu, como usuário, desejo ter uma página de meus projetos para visualizar todos os projetos em que estou inscrito

### ISSUE THREAD

**Issue by DiProjOrcestra** [DiProjOrcestra/orclamp#8]
## Descrição da Issue
Criar uma tela de meus projetos.
### Tasks: 
- [ ] Listar todos os projetos que a pessoa está;
- [ ] Permitir a pessoa pesquisar projetos;
- [ ] Permitir a pessoa filtrar os projetos.
